// This file was generated by Gemini.
import 'package:vector_math/vector_math_64.dart';

bool isTriangleAboveSquare(List<Vector3> triangle, double n) {
  // 1. Find a 2D point (x, y) where the triangle and square definitely overlap.
  Vector2? overlapPoint = _findOverlapPoint2D(triangle, n);
  
  // If there is no horizontal overlap, we don't care about the result
  if (overlapPoint == null) {
    return false; 
  }

  // 2. Mathematically construct the plane properties
  // Find two edge vectors sharing a vertex
  final ab = triangle[1] - triangle[0];
  final ac = triangle[2] - triangle[0];
  
  // The normal vector (A, B, C) is the cross product of the two edges
  final normal = ab.cross(ac);

  // If the plane is perfectly vertical (Z is 0), it has no meaningful height above the square
  if (normal.z.abs() < 1e-6) {
    return false;
  }

  // Find the plane constant D. Plane equation: Ax + By + Cz + D = 0 -> D = -(A*x + B*y + C*z)
  // Which is equivalent to negative dot product of the normal and any vertex.
  double constantD = -normal.dot(triangle[0]);

  // 3. Calculate the exact Z-height of the triangle at our overlap point.
  // Ax + By + Cz + D = 0  ->  Cz = -Ax - By - D  ->  z = (-Ax - By - D) / C
  double zAtOverlap = (-normal.x * overlapPoint.x - normal.y * overlapPoint.y - constantD) / normal.z;

  // 4. Return true if above the square (z > 0), false if below
  return zAtOverlap > 0;
}

/// Helper function to find any 2D point (x, y) shared by the square and triangle
Vector2? _findOverlapPoint2D(List<Vector3> triangle, double n) {
  final t0 = Vector2(triangle[0].x, triangle[0].y);
  final t1 = Vector2(triangle[1].x, triangle[1].y);
  final t2 = Vector2(triangle[2].x, triangle[2].y);
  final tVertices = [t0, t1, t2];

  // Define square corners
  final sVertices = [
    Vector2(-n, -n),
    Vector2(n, -n),
    Vector2(n, n),
    Vector2(-n, n),
  ];

  // Case 1: Check if any triangle vertex is inside the square
  for (var pt in tVertices) {
    if (pt.x >= -n && pt.x <= n && pt.y >= -n && pt.y <= n) {
      return pt;
    }
  }

  // Case 2: Check if any square corner is inside the triangle
  for (var pt in sVertices) {
    if (_pointInTriangle2D(pt, t0, t1, t2)) {
      return pt;
    }
  }

  // Case 3: Edges cross. Find any edge intersection.
  for (int i = 0; i < 3; i++) {
    final ta = tVertices[i];
    final tb = tVertices[(i + 1) % 3];
    for (int j = 0; j < 4; j++) {
      final sa = sVertices[j];
      final sb = sVertices[(j + 1) % 4];
      
      Vector2? intersect = _lineIntersection2D(ta, tb, sa, sb);
      if (intersect != null) {
        return intersect;
      }
    }
  }

  return null; // No horizontal overlap exists
}

/// Barycentric coordinate check to see if a 2D point is inside a 2D triangle
bool _pointInTriangle2D(Vector2 p, Vector2 a, Vector2 b, Vector2 c) {
  double s = (a.x - c.x) * (p.y - c.y) - (a.y - c.y) * (p.x - c.x);
  double t = (b.x - a.x) * (p.y - a.y) - (b.y - a.y) * (p.x - a.x);

  if ((s < 0) != (t < 0) && s != 0 && t != 0) return false;

  double d = (c.x - b.x) * (p.y - b.y) - (c.y - b.y) * (p.x - b.x);
  return d == 0 || (d < 0) == (s + t <= 0);
}

/// Finds the intersection point of two 2D line segments
Vector2? _lineIntersection2D(Vector2 a1, Vector2 a2, Vector2 b1, Vector2 b2) {
  double denominator = (a2.x - a1.x) * (b2.y - b1.y) - (a2.y - a1.y) * (b2.x - b1.x);
  if (denominator.abs() < 1e-6) return null; // Parallel lines

  double ua = ((a1.y - b1.y) * (b2.x - b1.x) - (a1.x - b1.x) * (b2.y - b1.y)) / denominator;
  double ub = ((a1.y - b1.y) * (a2.x - a1.x) - (a1.x - b1.x) * (a2.y - a1.y)) / denominator;

  if (ua >= 0 && ua <= 1 && ub >= 0 && ub <= 1) {
    return Vector2(a1.x + ua * (a2.x - a1.x), a1.y + ua * (a2.y - a1.y));
  }
  return null;
}